version: "3.9"

services:
    mysql:
        image: mariadb:10.8.3
        container_name: "mariadb"
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./.docker/mysql:/var/lib/mysql
            #- dbdata:/var/lib/mysql
        networks:
            - scs-teste

    laravel-app:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        container_name: "laravel-app"
        restart: always
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - scs-teste
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: "nginx"
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx:/etc/nginx/conf.d/
        working_dir: /var/www/html
        networks:
            - scs-teste
        depends_on:
            - laravel-app

    adminer:
        image: adminer
        container_name: "adminer"
        restart: always
        ports:
            - 8080:8080
        networks:
            - scs-teste

networks:
    scs-teste:
        driver: bridge
